### ISSUE TITLE
[Bug] Meeting hud patch let the name tag topmost overwrites other UIs

### ISSUE THREAD

**Issue by MapleEve** [CrowdedMods/CrowdedMod#34]
![image](https://user-images.githubusercontent.com/1845053/169660335-aeed7d54-84c3-4640-a5e7-74d9ca7a0889.png)

This might be an issue, we uses TOR as base mod, and guesser's guess UI is not topmost anymore.

**Comment by Galster-dev** [comment]
Hello!

This one should fix the issue https://github.com/CrowdedMods/CrowdedMod/suites/6605254862/artifacts/248254142
Could you try it and give feedback?

**Comment by MapleEve** [comment]
> Hello!
> 
> This one should fix the issue https://github.com/CrowdedMods/CrowdedMod/suites/6605254862/artifacts/248254142 Could you try it and give feedback?

Haven't play guesser in few days, but the task bar is okay now.

**Comment by MapleEve** [comment]
> Hello!
> 
> This one should fix the issue https://github.com/CrowdedMods/CrowdedMod/suites/6605254862/artifacts/248254142 Could you try it and give feedback?
![QQ截图20220526000437](https://user-images.githubusercontent.com/1845053/170328926-cf68c5b2-2c46-4c9e-b759-6deb43a24c1f.png)
![QQ截图20220526014228](https://user-images.githubusercontent.com/1845053/170328934-7a21bee5-729c-4a5d-baf2-c63fb8389603.png)

Still the same xD

**Comment by MapleEve** [comment]
https://github.dev/MapleEve/TheOtherRoles_RamboPlay/blob/a47fc37fa307e444b642d1809d1791abfc693918/TheOtherRoles/Patches/MeetingPatch.cs#L325-L326
`                buttonParent.localPosition = new Vector3(-3.47f + 1.75f * col, 1.5f - 0.45f * row, -5);
                buttonParent.localScale = new Vector3(0.55f, 0.55f, 1f);`

From the code, I think guesser UI is rendered in -5 Z

**Comment by Galster-dev** [comment]
there goes another one https://github.com/CrowdedMods/CrowdedMod/suites/6659873720/artifacts/251889722

**Comment by MapleEve** [comment]
> there goes another one https://github.com/CrowdedMods/CrowdedMod/suites/6659873720/artifacts/251889722

![image](https://user-images.githubusercontent.com/1845053/170342023-00ebebf3-1e7e-41c9-863a-c7b1a9f22fe2.png)

Guesser UI is fixed,

![image](https://user-images.githubusercontent.com/1845053/170342136-5ea17d20-5473-4076-a664-af1b9b9ab6b9.png)

Task is not.

**Comment by Galster-dev** [comment]
Can you send a picture of how it is supposed to look?

**Comment by MapleEve** [comment]
> Can you send a picture of how it is supposed to look?

the original patch during the meeting of TOR is broken.

I deleted the Crowded and the task bar is still override by nametags.

So I suspect the patch to allow <tab> key using during the meeting has its basic Z issue.

Thx, I just PRed to my fork, and this is very helpful.

If I encounter other bug in Submerged via this version or any bug in TOR-GM-H latest or TOU 3.10, I will report soon.

The crowded mod is fun, TYVM.

**Comment by Galster-dev** [comment]
@MapleEve You can also join our [Discord](https://discord.gg/XEc7PdDTyn) for easier communication!
